# Generated by Django 4.2.7 on 2023-11-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='name')),
                ('Description', models.TextField(verbose_name='description')),
                ('Price', models.IntegerField(verbose_name='price')),
            ],
        ),
    ]
